# Generated by Django 5.1.6 on 2025-02-25 09:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBookmark',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_feeds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_bookmarks',
                'constraints': [models.UniqueConstraint(fields=('user', 'feed'), name='unique_feed_bookmark')],
            },
        ),
        migrations.CreateModel(
            name='FeedLike',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='feeds.feed')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feed_likes',
                'constraints': [models.UniqueConstraint(fields=('user', 'feed'), name='unique_feed_like')],
            },
        ),
    ]
