# Generated by Django 5.1.6 on 2025-03-10 02:42

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0003_feedcomment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326),
        ),
    ]
