# Generated by Django 5.1.6 on 2025-03-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0005_populate_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
