# Generated by Django 5.1.6 on 2025-03-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0006_feed_thumbnail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='photo_taken_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
