# Generated by Django 5.2 on 2025-05-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0008_alter_feedcomment_options_feedcomment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='low_res_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feed',
            name='medium_res_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
