# Generated by Django 5.2 on 2025-05-01 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0009_feed_low_res_url_feed_medium_res_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='low_res_url',
        ),
        migrations.RemoveField(
            model_name='feed',
            name='medium_res_url',
        ),
    ]
