# Generated by Django 5.1.6 on 2025-02-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='background_color',
            field=models.CharField(default='#FFFFFF', max_length=10),
        ),
        migrations.AddField(
            model_name='album',
            name='background_pattern',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
