# Generated by Django 5.1.6 on 2025-02-15 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='pbkdf2_sha256$870000$obVOVDbDgSHw2tNTbteN22$ZKN2opftjtqW+0HB29eiDF6ebKHH5KOBTLfst6f3GD4=', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
